# Generated by Django 3.0.14 on 2022-11-09 19:24

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.TextField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SessionState',
            fields=[
                ('session_id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('state', models.CharField(max_length=200, null=True)),
                ('data', jsonfield.fields.JSONField(null=True)),
                ('phone', models.CharField(max_length=20)),
                ('context', models.CharField(max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
